runtime: nodejs20
service: default  


handlers:
- url: /static
  static_dir: build/static

- url: /(.*\.(json|js|ico|png|svg|jpg|jpeg|gif|woff|woff2|ttf|eot|css|map))$
  static_files: build/\1
  upload: build/.*\.(json|js|ico|png|svg|jpg|jpeg|gif|woff|woff2|ttf|eot|css|map)$

- url: /.*
  static_files: build/index.html
  upload: build/index.html
